version: '2'

services:

  web:
    build:
      context: .
    environment:
      RAILS_LOG_TO_STDOUT: 1
      RAILS_SERVE_STATIC_FILES: 1
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SES_SMTP_HOST: ${SES_SMTP_HOST}
      SES_SMTP_USERNAME: ${SES_SMTP_USERNAME}
      SES_SMTP_PASSWORD: ${SES_SMTP_PASSWORD}
    ports:
      - 80:3000
    command: bash -c "bundle install --without test && bundle exec rails db:migrate && bundle exec rails assets:precompile && bundle exec rails s -b 0.0.0.0"
    privileged: true
    volumes:
      - .:/code
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: '10m'
