# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83476dd853650ef07f0610f7a7c879c038cb5a102ccff07d8461afe6784a46ba5187e12eb8808f00a65ae13ae83d01a6a5e091ca94414d7cc361aeacb1c763db

test:
  secret_key_base: e0bb7dbabe0bb3b19338c896f8f27ea96feb08a16a9df13132b363e816e682ef102b86c49d2058e90a697ab8f4ff3a32e973388472fa6a687c92c1f928f45599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
